---
title: Bluelabs
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: bluelabs@gmail.com
description: A blog about my favorite web conferences.
url: http://bluelabs.com
twitter_username: Blue_Labs
markdown: kramdown
permalink: "/:title"
github:
  url: http://localhost:4000
  baseurl: NewHP
